root = "."
tmp_dir = "tmp"

[build]
  pre_cmd = ["sqlc generate"]
  cmd = "go build -o ./tmp/main ./cmd/api"
  bin = "./tmp/main"
  include_ext = ["go", "sql", "yaml"]
  exclude_dir = ["tmp", "internal/database"]
  exclude_regex = ["_test.go"]
  delay = 500
  kill_delay = "1s"
  send_interrupt = true   # graceful shutdown de Fiber

[misc]
  clean_on_exit = true
